// Package models contains the types for schema ''.
package models

// GENERATED BY XO. DO NOT EDIT.

// ChatResult represents a row from '[custom chat_result]'.
type ChatResult struct {
	PrimaryID int    // primary_id
	ChatID    int    // chat_id
	Type      string // type
	Abandoned int    // abandoned
	UserID    int    // user_id
	UserName  string // user_name
	FirstName string // first_name
	LastName  string // last_name
	OpenTime  string // open_time
	LastTime  string // last_time
	State     string // state
	Params    string // params
}

// ChatResultsByParam runs a custom query, returning results as ChatResult.
func ChatResultsByParam(db XODB, param string) ([]*ChatResult, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`* ` +
		`FROM chat ` +
		`WHERE ` +
		`params like "%" || ? || "%"`

	// run query
	XOLog(sqlstr, param)
	q, err := db.Query(sqlstr, param)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*ChatResult{}
	for q.Next() {
		cr := ChatResult{}

		// scan
		err = q.Scan(&cr.PrimaryID, &cr.ChatID, &cr.Type, &cr.Abandoned, &cr.UserID, &cr.UserName, &cr.FirstName, &cr.LastName, &cr.OpenTime, &cr.LastTime, &cr.State, &cr.Params)
		if err != nil {
			return nil, err
		}

		res = append(res, &cr)
	}

	return res, nil
}
